language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t amudhan/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true amudhan/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-829162834943"
  bucket_path: "docker-react"
  access_key_id: 
      secure: $AWS_ACCESS_KEY
  secret_access_key:
      secure: $AWS_SECRET_KEY
  on:
    branch: master
